version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./backups:/home/backups
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    expose:
      - "9000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/code
