version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./backups:/home/backups
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dbPassword
      - POSTGRES_USER=dbUsername
      - POSTGRES_DB=dbName
  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    expose:
      - "9000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/code
