# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-29 23:35
from __future__ import unicode_literals

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=128, validators=[django.contrib.auth.password_validation.validate_password], verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('flagged', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('heroImage', models.TextField(blank=True, null=True)),
                ('github_id', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
