# Generated by Django 2.1.2 on 2018-10-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='tags',
            field=models.ManyToManyField(related_name='challenges', to='challenges.Tag'),
        ),
    ]
